### ISSUE TITLE
Otsikon paikka 

### ISSUE THREAD

**Issue by spmima** [datakurre/vakioasiakirja#6]
Näyttäisi siltä (ainakin minun tulosteissani) että vastaajan osoitetietojen jälkeen tuleva viitetieto / tunnistetieto on vähän liian lähellä osoitetietoja. Tästä seuraa että dokumentin "Asiaotsikko" jää paperissa minusta hiukan liian ylös.  

Laskin, että monessa SFS 2487 esittelydokumentissa osoitetietojen ja tunnistetietojen välillä on viisi riviä. Sitä, onko tällainen määräys standardissa en pääse tarkistamaan, koska  SFS  pyytää noin 70 euroa vakioasiakirjastandardista, jota kaiken lisäksi ollaan parhaillaan muuttamassa "näyttöystävälliseen muotoon". Siksi en tiedä, kannattaako tätä nyt enempää säätää, mutta panen nyt kuitenkin tämän tiedoksesi.  

Aikanaan minua opetettiin, että mitä korkeammalle taholle asiakirja lähetetään, sitä alemmaksi paperilla otsikko laitetaan. Alhaalla olevalla otsikolla ikäänkuin kumarretaan nöyrästi. Mallia "Hovioikeudelle otsikko 10 riviä alalaidasta, Korkeimmalle oikeudelle 5 riviä alalaidasta".  Siten tuo SFS 2487 edustaa aika demokraattista asennetta!

**Comment by datakurre** [comment]
Kauan sitten SFS julkaisi koostekirjaa Toimiston asiakirjat, jossa näitä sai koostetusti suhteellisen kohtuullisella hinnalla.

Vuoden 2007 standardissa asiakirja on tosiaan  neljään alueseen: 

* ylätunnistetiedotta
* vastaanottajan yhteystiedot
* asiasisältö
* alatunnistetiedot

Jos ensimmäinen ylätunnisteen rivi olisi ensimmäinen rivi R1,

* vastaanottajan yhteystiedot alkaisivat riviltä R8
* aiasisältö riviltä R16
* ja alatunnistetiedot riviltä R63 (neljä riviä + 1cm sivun alareunasta)

En taida vieläkään ostata tuollaisia täysin kiinteitä alueita LaTeX-pohjassa, mutta yritin kasvattaa väliä vastaanottajan ja sisällön välillä:

https://github.com/datakurre/vakioasiakirja/blob/68142e345e03b3a8fdac9d9638a94a551fadfa2b/vakioasiakirja.cls

Alatunniste näyttäisi jääneen tästä pohjasta kokonaan pois.

**Comment by spmima** [comment]
Mahtavaa! minusta tämä on nyt aivan kohdallaan.
